# Generated by Django 5.1.1 on 2024-09-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('main', 'Main Image'), ('front', 'Front Image'), ('back', 'Back Image'), ('left', 'Left Image'), ('right', 'Right Image'), ('modelOne', 'Model Image One'), ('modelTwo', 'Model Image Two')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
